name: Crossbuild Go Binary

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x

      # - name: Install cross-compilation dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu gcc-multilib gcc-mingw-w64

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build for Linux amd64
        env:
          GOOS: linux
          GOARCH: amd64
          CC: gcc
          CXX: g++
          CGO_ENABLED: 1
        run: go build -o output/${{ env.GOOS }}-${{ env.GOARCH }} ./...

      - name: Build for Linux arm64
        env:
          GOOS: linux
          GOARCH: arm64
          CC: aarch64-linux-gnu-gcc
          CXX: aarch64-linux-gnu-g++
          CGO_ENABLED: 1
        run: go build -o output/${{ env.GOOS }}-${{ env.GOARCH }} ./...

      - name: Build for MacOS amd64
        env:
          GOOS: darwin
          GOARCH: amd64
          CC: x86_64-apple-darwin20.2-clang
          CXX: x86_64-apple-darwin20.2-clang++
          CGO_ENABLED: 1
        run: go build -o output/${{ env.GOOS }}-${{ env.GOARCH }} ./...

      - name: Build for MacOS arm64
        env:
          GOOS: darwin
          GOARCH: arm64
          CC: arm64-apple-darwin20.2-clang
          CXX: arm64-apple-darwin20.2-clang++
          CGO_ENABLED: 1
        run: go build -o output/${{ env.GOOS }}-${{ env.GOARCH }} ./...

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: output/
