name: build

on:
  push:
  pull_request:

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.20
          dest: build
          prefix: ggt
          targets: linux/amd64,linux/arm64,darwin/amd64,darwin/arm64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          pkg: main.go
